language: python
python:
  - "3.5"
# command to install dependencies
sudo: required
services:
  - docker
install:
- docker pull mysql:5.7.14
- docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
- docker-compose up -d
- docker ps
# install: "pip install -r requirements.txt"
# command to run tests
script:
  - docker exec -it cs4501_web_1 bash -c "cd /web;python manage.py test"
  - docker exec -it cs4501_exp_1 bash -c "cd /exp;python manage.py test"
notifications:
  email: false
