models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ~/cs4501/app:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install djangorestframework; /app/jbay/manage.py makemigrations; /app/jbay/manage.py migrate; /app/jbay/manage.py loaddata shoe_data.json; mod_wsgi-express start-server --reload-on-changes /app/jbay/jbay/wsgi.py"
