models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ~/build/antlsung/cs4501/app:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install djangorestframework; /app/jbay/manage.py makemigrations; /app/jbay/manage.py migrate; /app/jbay/manage.py loaddata shoe_data.json; mod_wsgi-express start-server --reload-on-changes /app/jbay/jbay/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   ports:
      - "8002:8000"
      - "8001"
      - "8000"
   volumes:
      - ~/build/antlsung/cs4501/exp:/exp
   command: bash -c "pip install requests; cd /exp; mod_wsgi-express start-server --reload-on-changes /exp/exp/wsgi.py"

web:
  image: tp33/django
  links:
    - exp:exp-api
  ports:
    - "8000:8000"
    - "8002"
    - "8001"
  volumes:
    - ~/build/antlsung/cs4501/web:/web
  command: bash -c "pip install djangorestframework; pip install requests; cd /web; mod_wsgi-express start-server --reload-on-changes /web/web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ~/build/antlsung/cs4501/batch:/batch
   command: bash -c "cd /batch/batch; python batch.py;"
